image: jangrewe/gitlab-ci-android

stages:
- build

before_script:
- cd Luca
- export GRADLE_USER_HOME=$(pwd)/.gradle
- chmod +x ./gradlew

cache:
  key: ${CI_PROJECT_ID}
  paths:
  - .gradle/

build:
  stage: build
  script:
  - ./gradlew :app:testDebug :app:testProduction
  artifacts:
    when: always
    reports:
      junit: Luca/app/build/test-results/**/TEST-*.xml
