image: jangrewe/gitlab-ci-android

stages:
- test

before_script:
- cd Luca
- export GRADLE_USER_HOME=$(pwd)/.gradle
- chmod +x ./gradlew

cache:
  key: ${CI_PROJECT_ID}
  paths:
  - .gradle/

test:
  stage: build
  script:
  - ./gradlew :app:test
